global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: "prowlarr-exporter"
    static_configs:
      - targets: ["prowlarr-exporter:9710"]
  - job_name: "radarr-exporter"
    static_configs:
      - targets: ["radarr-exporter:9708"]
  - job_name: "sonarr-exporter"
    static_configs:
      - targets: ["sonarr-exporter:9707"]
  - job_name: json
    metrics_path: /probe
    params:
      # The name of the module defined by json-exporter-config.yaml
      module: [jellyfin] 
    static_configs:
      - targets:
        # Use the Sessions endpoint to see actively playing items
        - http://jellyfin:8096/jellyfin/Sessions
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json-exporter:7979 # The exporter's hostname:port