---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- group: Media
  items:
    - name: Sonarr
      icon: sonarr.png
      href: https://home.brettswift.com/sonarr
      description: Series management
    - name: Radarr
      icon: radarr.png
      href: https://home.brettswift.com/radarr
      description: Movies management
    - name: Lidarr
      icon: lidarr.png
      href: https://home.brettswift.com/lidarr
      description: Music management

- group: Download
  items:
    - name: qBittorrent
      icon: qbittorrent.png
      href: https://home.brettswift.com/qbittorrent
      description: Bittorrent client
    - name: Prowlarr
      icon: prowlarr.png
      href: https://home.brettswift.com/prowlarr
      description: Indexers management
    - name: Bazarr
      icon: bazarr.png
      href: https://home.brettswift.com/bazarr
      description: Subtitles management
    - name: Sabnzbd
      icon: sabnzbd.png
      href: https://home.brettswift.com/sabnzbd
      description: Usenet

- group: Media Server
  items:
    - name: Jellyfin
      icon: jellyfin.png
      href: https://home.brettswift.com/jellyfin
      description: Media server

- group: Utilities
  items:
    - name: Traefik Dashboard
      icon: traefik.png
      href: https://home.brettswift.com/dashboard
      description: Traefik management
    - name: Homepage
      icon: homepage.png
      href: https://home.brettswift.com/
      description: Homepage dashboard


