---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- group: Media
  items:
    - name: Sonarr
      icon: sonarr.png
      href: /sonarr
      description: Series management
    - name: Radarr
      icon: radarr.png
      href: /radarr
      description: Movies management
    - name: Lidarr
      icon: lidarr.png
      href: /lidarr
      description: Music management

- group: Download
  items:
    - name: qBittorrent
      icon: qbittorrent.png
      href: /qbittorrent
      description: Bittorrent client
    - name: Prowlarr
      icon: prowlarr.png
      href: /prowlarr
      description: Indexers management
    - name: Bazarr
      icon: bazarr.png
      href: /bazarr
      description: Subtitles management
    - name: Sabnzbd
      icon: sabnzbd.png
      href: /sabnzbd
      description: Usenet

- group: Media Server
  items:
    - name: Jellyfin
      icon: jellyfin.png
      href: /jellyfin
      description: Media server

- group: Utilities
  items:
    - name: Traefik Dashboard
      icon: traefik.png
      href: /dashboard
      description: Traefik management
    - name: Homepage
      icon: homepage.png
      href: /
      description: Homepage dashboard


