server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

#scrape_configs:
#  - job_name: system
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#        refresh_interval: 5s  # Refresh every 5 seconds
#    relabel_configs:
#      - source_labels: [__meta_docker_container_name]
#        target_label: container_name
#      - source_labels: [__meta_docker_container_image]
#        target_label: container_image
#      - source_labels: [__meta_docker_container_id]
#        target_label: container_id
#      - source_labels: [__meta_docker_container_labels]
#        target_label: container_labels
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          __path__: /var/log/*log
#
#  - job_name: docker
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: docker_logs
#          __path__: /var/lib/docker/containers/*/*-json.log